feat(baseline): Add Arima baseline
Mosqlimate-project/mosqlimate-client pull request #11
Opened 2024-06-04 10:19 UTC by eduardocorrearaujo

@fccoelho This is the implementation of the ARIMA baseline. Please review it when you have some time.

2024-06-04 13:00 UTC, fccoelho requested changes

2024-06-04 13:00 UTC, fccoelho commented on mosqlient/requests.py
Maybe try to find a new name for this module. "requests" is the name of the library used here , and this can cause name conflicts, depending on how the user imports it.

2024-06-04 15:31 UTC, eduardocorrearaujo commented on mosqlient/requests.py
What do you suggest?

2024-06-04 19:43 UTC, eduardocorrearaujo commented on examples/baseline_model.ipynb
Could you explain it better, please?  
```
Then it may be interesting to add a forecast curve in the same out-of-sample prediction plot, for comparison.
```

During the out-of-sample prediction, what is done is essentially the forecast step multiple times. For example, if our data has indices 1-16 and the horizon is 4, the first forecast is for indices 1-4. After that, we update the Arima model using the actual observations of indices 1-4 and forecast the indices 5-8. This is done until predictions are generated for all the out-of-sample intervals.

2024-06-05 10:09 UTC, eduardocorrearaujo commented on mosqlient/requests.py
I think `apiaccess` is better since inside the datastore, there is a script called `api`.

2024-06-06 13:33 UTC, eduardocorrearaujo commented on examples/baseline_model.ipynb
Okay, now I understand your point. The `auto_arima` package just provides two methods: `predict_in_sample` and `predict`

I will compare the `auto_arima` implementation with `statsmodels` to see if there are relevant changes in the performance with the same parameters.

2024-06-11 12:52 UTC, eduardocorrearaujo commented on mosqlient/__main__.py
>  from mosqlient.cli import main
I created a issue #14 to Lua work on it.

2024-06-11 15:48 UTC, fccoelho approved these changes

2024-06-11 16:11 UTC, merged