30 improve documentation
Mosqlimate-project/mosqlimate-client pull request #31
Opened 2024-08-07 20:52 UTC by fccoelho

2024-08-08 01:08 UTC, luabida commented
@fccoelho  you may have some conflicts in your PR, could you please rebase it with the latest commit in the ~HEAD?

2024-08-08 11:50 UTC, eduardocorrearaujo requested changes
No notebook

2024-08-08 11:50 UTC, eduardocorrearaujo commented on docs/tutorials/Using Mosqlient from R.ipynb
Nesse notebook é indicado a instalação da versão `1.2.2` do pacote do mosqlient mas no repositório do sprint está indicada a versão `1.3.1`, nesse notebook deve constar essa versão também.

2024-08-08 11:50 UTC, eduardocorrearaujo commented on docs/tutorials/datastore.ipynb
O notebook está com algumas células indicando erros.

2024-08-08 11:50 UTC, eduardocorrearaujo commented on docs/tutorials/models.ipynb
O notebook está com algumas células indicando erros.

2024-08-08 11:53 UTC, fccoelho commented on docs/tutorials/Using Mosqlient from R.ipynb
O R tem algum problema de cache de pacotes. Não sei com resolver isso.

2024-08-08 11:58 UTC, fccoelho commented on docs/tutorials/datastore.ipynb
Sim

```python
ConnectionRefusedError: [Errno 111] Connect call failed ('0.0.0.0', 8042)
```
Acho que este erro tem a ver com o asyncio

2024-08-08 11:59 UTC, maxbiostat commented on docs/tutorials/Using Mosqlient from R.ipynb
Como assim?

2024-08-08 12:02 UTC, fccoelho commented on docs/tutorials/models.ipynb
esse erro é por que o exemplo dado é inválido:

```python
client = Client("<USER>:<API-KEY>", "dev")
```
recomendo que seja aberto outro issue como bug

2024-08-08 12:19 UTC, fccoelho commented on docs/tutorials/Using Mosqlient from R.ipynb
O problema é que a última versao da Mosqlient está com o Python pinado para <3.12 e aqui em casa eu rodo o python 3.12. @luabida acho que para a próxima release precisamos remover este pin.

2024-08-09 13:36 UTC, fccoelho commented on docs/tutorials/Using Mosqlient from R.ipynb
Como este PR é para Documentação, podemos mover isso para um issue separado e mergear esse

2024-08-09 13:48 UTC, fccoelho commented on docs/tutorials/Using Mosqlient from R.ipynb
it's open as issue #33

2024-08-09 13:49 UTC, fccoelho commented on docs/tutorials/datastore.ipynb
it's now issue #34

2024-08-09 14:25 UTC, merged